---
- hosts: local
  roles:
    - useraddgw

- hosts: adserver
  vars:
    ansible_user: Administrator
    #ansible_password: 
    ansible_port: 5985
    ansible_connection: winrm
    #ansible_winrm_realm: YOUR.HOST.DOMAIN
    ansible_winrm_server_cert_validation: ignore
    ansible_winrm_transport: kerberos
    ansible_winrm_kinit_mode: managed
    ansible_winrm_kinit_cmd: /usr/bin/kinit
    ansible_winrm_service: HTTP
    #ansible_winrm_kerberos_delegation: false
    #ansible_winrm_kerberos_hostname_override:
  roles:
    - useradd

- hosts: local
  tasks:
    - include: roles/useraddgw/tasks/notification.yml
